name: Go Coverage
on: [push]

jobs:
  test:
    name: Coverage
    strategy:
      matrix:
        go-version:
          - "1.20"
          - "1.21"
          - "1.22"
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Test with coverage
        run: go test -v -coverprofile="coverage.out" ./

      - name: Upload coverage to Codecov
        if: matrix.go-version == '1.22'
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out
          fail_ci_if_error: true
          flags: unittests
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
